### ISSUE TITLE
Support for Pytorch 2.1 and newer

### ISSUE THREAD

**Issue by jamesobutler** [mazurowski-lab/SlicerSegmentAny3D#1]
Does SegmentAny3D specifically require the Cuda 11.7 compute platform and not anything newer? Or even support for CPU only?

https://github.com/mazurowski-lab/SlicerSegmentAny3D/blob/e33d0af23ef6d6458a95074b47374a2697582209/SegmentAny3D/SegmentAny3D.py#L122-L126

I typically have [SlicerTotalSegmentator](https://github.com/lassoan/SlicerTotalSegmentator) installed in my Slicer version and it will pull in latest pytorch. Starting with pytorch 2.1, the available compute platforms are CUDA 11.8 and CUDA 12.1. CUDA 11.7 is not available for latest PyTorch which is why SegmentAny3D is pulling in the older pytorch 2.0.x series.

**Comment by Zaferyildiz** [comment]
Thank you for the recommendation. PyTorch version condition is removed with the latest commit.
