### ISSUE TITLE
Packaging not working for distribution on Slicer ExtensionsIndex

### ISSUE THREAD

**Issue by jamesobutler** [mazurowski-lab/SlicerSegmentAny3D#3]
https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html#distribute-an-extension

> While it is possible to develop Python-based extensions without a [local extension build](https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html#extension-build), creating one can significantly expedite the development cycle. This allows you to promptly confirm that the extension can be properly packaged and distributed, providing a quicker feedback loop compared to waiting for the daily build and test reports.

Below is a traceback of the extension ZIP when installed from local file through the Slicer Extensions Manager.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\butlej30383\AppData\Local\slicer.org\Slicer 5.7.0-2024-02-19\lib\Python\Lib\imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:/Users/butlej30383/AppData/Local/slicer.org/Slicer 5.7.0-2024-02-19/slicer.org/Extensions-32725/SegmentAny3D/lib/Slicer-5.7/qt-scripted-modules/SegmentAny3D.py", line 16, in <module>
    from models import cfg
ModuleNotFoundError: No module named 'models'
[Qt] loadSourceAsModule - Failed to load file "C:/Users/butlej30383/AppData/Local/slicer.org/Slicer 5.7.0-2024-02-19/slicer.org/Extensions-32725/SegmentAny3D/lib/Slicer-5.7/qt-scripted-modules/SegmentAny3D.py"  as module "SegmentAny3D" !
[Qt] Fail to instantiate module  "SegmentAny3D"
[Qt] The following modules failed to be instantiated:
[Qt]    SegmentAny3D

```

I observe the following files in the extension ZIP lib directory:
```
C:/D/SlicerSegmentAny3D-bin/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/lib\
C:/D/SlicerSegmentAny3D-bin/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/lib\Slicer-5.7
C:/D/SlicerSegmentAny3D-bin/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/lib\Slicer-5.7\qt-scripted-modules
C:/D/SlicerSegmentAny3D-bin/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/lib\Slicer-5.7\qt-scripted-modules\Resources
C:/D/SlicerSegmentAny3D-bin/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/lib\Slicer-5.7\qt-scripted-modules\Resources\Icons
C:/D/SlicerSegmentAny3D-bin/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/lib\Slicer-5.7\qt-scripted-modules\Resources\Icons\SegmentAny3D.png
C:/D/SlicerSegmentAny3D-bin/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/lib\Slicer-5.7\qt-scripted-modules\Resources\UI
C:/D/SlicerSegmentAny3D-bin/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/lib\Slicer-5.7\qt-scripted-modules\Resources\UI\SegmentAny3D.ui
C:/D/SlicerSegmentAny3D-bin/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/lib\Slicer-5.7\qt-scripted-modules\SegmentAny3D.py
C:/D/SlicerSegmentAny3D-bin/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/32725-win-amd64-SegmentAny3D-gite33d0af-2024-03-14/lib\Slicer-5.7\qt-scripted-modules\SegmentAny3D.pyc
```
This matches what is specified in the following which does not include anything in the[ SlicerSegmentAny3D/SegmentAny3D/models](https://github.com/mazurowski-lab/SlicerSegmentAny3D/tree/e33d0af23ef6d6458a95074b47374a2697582209/SegmentAny3D/models) directory:
https://github.com/mazurowski-lab/SlicerSegmentAny3D/blob/e33d0af23ef6d6458a95074b47374a2697582209/SegmentAny3D/CMakeLists.txt#L5-L12

**Comment by Zaferyildiz** [comment]
@jamesobutler I couldn't build the extension on my local since cmake-gui application gives me Slicer_DIR-NOTFOUND error even if I replaced with a folder I create. However, I added /models folder to MODULE_PYTHON_RESOURCES in the last commit. Does this indicate a solution for this problem? If it does not, what should be a proper Slicer_DIR value to build the extension locally?

**Comment by jamesobutler** [comment]
`Slicer_DIR` should be filled out to be your inner Slicer-build directory such as `C:\S5R\Slicer-build`. This is a directory with filled content from having built 3D Slicer from source (https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/index.html).

For testing and debugging the packaging of your extension to make sure it is distributed successfully through the Slicer Extensions Manager, you should build 3D Slicer from source so that you can build your extension against that source tree. See https://slicer.readthedocs.io/en/latest/developer_guide/extensions.html#build-an-extension.

**Comment by Zaferyildiz** [comment]
@jamesobutler I have edited CMakeList.txt file and the error you mentioned is cleared now.
