### ISSUE TITLE
Temporary files are under revision control

### ISSUE THREAD

**Issue by lassoan** [mazurowski-lab/SlicerSegmentAny3D#5]
This folder contains temporary files that should be removed (they unnecessarily increase the repository size):
- https://github.com/mazurowski-lab/SlicerSegmentHumanBody/tree/main/SegmentHumanBody/__pycache__
- https://github.com/mazurowski-lab/SlicerSegmentHumanBody/tree/main/SegmentHumanBody/models/__pycache__
- https://github.com/mazurowski-lab/SlicerSegmentHumanBody/tree/main/SegmentHumanBody/models/sam/__pycache__

**Comment by Zaferyildiz** [comment]
@lassoan Mentioned folders are deleted. Thank you for the suggestion.
